### ISSUE TITLE
codum.token

### ISSUE THREAD

**Issue by infohata** [codum-io/codum-core#3]
# Token Implementation
* file space: contracts/
* files: codum.token.hpp, codum.token.cpp
* compiles to: codum.token.abi, codum.token.wast, codum.token.wasm
* fork of eos.token
* symbol: CODUM
* account: codumreserve
* max supply 428000000.0000 c_
* decimals: 4
* launch date: 2019-09-09 09:09:09 UTC (to be used as launch date for launch lock function)

## Table for storing the gradually unlocking instructions
* table `gradunlock`
  * `locked_until uint_64 (datetime) primary`
  * `lock_threshold uint_8`
* affected accounts are ones claiming tokens from `gradissuer` accounts: codumcontrib, codumfounder, codumadvisor;
* until locked_until=2019-09-09 12:00 UTC: lock_threshold=90 // 90% of distributed balance;
* until locked_until=2020-03-09 12:00 UTC: lock_threshold=80 // 80% of distributed balance;
* until locked_until=2020-09-09 12:00 UTC: lock_threshold=70 // 70% of distributed balance;
* until locked_until=2021-03-09 12:00 UTC: lock_threshold=60 // 60% of distributed balance;
* until locked_until=2021-09-09 12:00 UTC: lock_threshold=50 // 50% of distributed balance;
* until locked_until=2022-03-09 12:00 UTC: lock_threshold=40 // 40% of distributed balance;
* until locked_until=2022-09-09 12:00 UTC: lock_threshold=30 // 30% of distributed balance;
* until locked_until=2023-03-09 12:00 UTC: lock_threshold=20 // 20% of distributed balance;
* until locked_until=2023-09-09 12:00 UTC: lock_threshold=10 // 10% of distributed balance;
comment: maybe hardcoding these would be more optimal

## Transfer Lock table implementation
the table `transferlock`:
* id, uint_64, primary, auto_increment
* account, account_name, index
* locked_balance, uint64_t
* locked_until, uint_64 (datetime)

## Lock Function
`private void lock(to, quantity, locked_until, threshold)`
* find a record with `account=to` in `transferlock` table with `locked_until` set to launch date
  * create if not found with `locked_balance=quantity*threshold/100`
* if found, update the record by setting `locked_balance+=quantity*threshold/100`

## Launch Lock function
`public void launch_lock(to, quantity)`
* issuer permission check with codumreserve
* `lock(to, quantity, launch_date, 100)`

## Gradual Lock function
`public void gradual_lock(to, quantity)`
* gradissuer permission check with codumreserve
* for each `locked_until` from `gradunlock` table as `lt`
  * `lock(to, quantity, lt.locked_until, lt.lock_threshold)`

## Distribute Tokens function
`public void distribute_tokens(from, to, quantity, memo)`
* requires authentication of `from` account
* requires `issuer` or `gradissuer` permission granted to `from` account to continue
* if `from` has issuer permission execute `launch_lock(to, quantity)`
* else execute `gradual_lock(to, quantity)`
* execute `transfer(from, to, quantity, memo)`

## Transfer Function Implementation
`public void transfer(from, to, quantity, memo)`
* find a record with `account=from` in `transferlock` table with `locked_until` later than now, take the first record ordered by date ascending as `locked`
  * if found, `eosio_assert(quantity.amount <= from.balance.amount - locked.locked_balance, "locked tokens cannot be transferred")`
* continue normal eosio.token::transfer()

## Rates
`#define NETWORK_EOS 0`
`#define NETWORK_EUR 1`
`#define NETWORK_USD 2`
`#define NETWORK_ETH 3`

Table `rate`
* network, uint8_t, primary key, unique
* rate, uint64_t (asset.amount)
* updated, uint64_t (epoch time)

## Function to add rate
`public void update_rate(network, rate)`
* require permission `codumreserve@active` or `codumreserve@issue`
* create or update an entry in `rates` table with `network` and set `rate` and updated=now()

### other properties as in eosio.token

**Comment by akhiltiwari-tr** [comment]
Hello @infohata,

> inherits eos.token
**I am getting the below error in automatic abi generation when inheriting the eosio.token contract class...**
```

> 3251580ms thread-0   main.cpp:105                  main           ] 999999 abi_generation_exception: Unable to generate abifind_struct(method_name) == nullptr: action already exists create
>     {"method_name":"create"}    thread-0  abi_generator.cpp:132 operator()
>     {}
>     thread-0  abi_generator.cpp:190 inspect_type_methods_for_actions
> 
>     {}
>     thread-0  abi_generator.cpp:306 handle_decl
>     {"decl_location":"/home/rails/files/projects/eos/contracts/demo/demo.cpp:6:7"}
>     thread-0  abi_generator.cpp:44 handle_tagdecl_definition
> 3251580ms thread-0   main.cpp:105                  main           ] output: {"version":"eosio::abi/1.0","types":[],"structs":[{"name":"create","base":"","fields":[{"name":"issuer","type":"name"},{"name":"maximum_supply","type":"asset"}]},{"name":"issue","base":"","fields":[{"name":"to","type":"name"},{"name":"quantity","type":"asset"},{"name":"memo","type":"string"}]},{"name":"transfer","base":"","fields":[{"name":"from","type":"name"},{"name":"to","type":"name"},{"name":"quantity","type":"asset"},{"name":"memo","type":"string"}]}],"actions":[{"name":"create","type":"create","ricardian_contract":""},{"name":"issue","type":"issue","ricardian_contract":""},{"name":"transfer","type":"transfer","ricardian_contract":""}],"tables":[],"ricardian_clauses":[],"error_messages":[],"abi_extensions":[]}

```
Even if we manually create the abi, it does not work as the actions are missing from the resultant .wasm of the codum.token contract.
**I think we should make inline calls to the actions of the eosio.token contract. Let me know if you disagree**

**Comment by infohata** [comment]
yes, looks like inheritance is flawed. Can we make it with inline actions but restrict calling `eosio.token::transfer()` directly from codum.token via `cleos push`?

**Comment by akhil-pro** [comment]
Yes, modifying eosio.token would give us a great deal of flexibility with our tokens.  This would also mean that our accounts and token table would be in a different scope than the eosio.token. This way we will be completely isolated from the other tokens/accounts. I think we should go with this approach to avoid the permission mess of the inline actions. What do you think?

**Comment by infohata** [comment]
then clone eosio.token - and displace the methods as in task.

**Comment by akhil-pro** [comment]
**ESTIMATE FOR ISSUE #3**
1. Testing codum token creation  logic in the codum.token smart contract should be done by EOD today.(10/07/2018)
2. Create the transferlock and gradualtransferunlock tables by EOD today. (10/07/2018)
3. Implement the lock and unlock functions by 11/07/2018 EOD
4. Implement the distribute and transfer actions by 12/07/2018 evening.

**Comment by infohata** [comment]
make it CODUM for now. eosDAC overcame this, i'm looking into that

**Comment by akhil-pro** [comment]
Hello,
Can you please breif me about the transfer lock and transfer unlock concept in the codum.token and how does it relate to any other eosio token?

for example, a regular eosio.token is created with a symbol and a max supply and then it is issued by the issuer to any eos account. Once the token is issued to any account (say jon), he can transfer it to any other account. 

The account with total tokens it posses is stored in the "accounts" table and the token that has been issued is stored in the stat table with the max supply and the total amount that has been issued thus far. 

Could you please provide me with a parallel b/w eosio.token and the codum.token (especially the locking functionality)

**Comment by infohata** [comment]
actually once we forked eosio.token, we do not need to relate it. 
Just make the default transfer function to check for locks as described. 
Then make another transfer function to check for the `issue` or `gradissue` permissions in the account the contract will be launched. We plan to launch contract as `codumreserve` (permissions added in the mainnet).

**Comment by infohata** [comment]
or, it can be the same function, and it checks for either permission or locks. As I am thinking now, this would be the most optimal way to do it with just one `transfer` function.

**Comment by infohata** [comment]
updated transfer function in the description according to my last comment

**Comment by infohata** [comment]
also fixed table/field/function names to C++ convention - too many languages :)
